// Code generated by sqlc. DO NOT EDIT.
// source: dataproductcollections.sql

package gensql

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createDataproductCollection = `-- name: CreateDataproductCollection :one
INSERT INTO dataproduct_collections (
	"name",
	"description",
	"slug",
	"repo",
	"team",
	"keywords"
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6
) RETURNING id, name, description, slug, repo, created, last_modified, team, keywords, tsv_document
`

type CreateDataproductCollectionParams struct {
	Name        string
	Description sql.NullString
	Slug        string
	Repo        sql.NullString
	Team        string
	Keywords    []string
}

func (q *Queries) CreateDataproductCollection(ctx context.Context, arg CreateDataproductCollectionParams) (DataproductCollection, error) {
	row := q.db.QueryRowContext(ctx, createDataproductCollection,
		arg.Name,
		arg.Description,
		arg.Slug,
		arg.Repo,
		arg.Team,
		pq.Array(arg.Keywords),
	)
	var i DataproductCollection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.Repo,
		&i.Created,
		&i.LastModified,
		&i.Team,
		pq.Array(&i.Keywords),
		&i.TsvDocument,
	)
	return i, err
}

const deleteDataproductCollection = `-- name: DeleteDataproductCollection :exec
DELETE FROM dataproduct_collections WHERE id = $1
`

func (q *Queries) DeleteDataproductCollection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDataproductCollection, id)
	return err
}

const getDataproductCollection = `-- name: GetDataproductCollection :one
SELECT id, name, description, slug, repo, created, last_modified, team, keywords, tsv_document FROM dataproduct_collections WHERE id = $1
`

func (q *Queries) GetDataproductCollection(ctx context.Context, id uuid.UUID) (DataproductCollection, error) {
	row := q.db.QueryRowContext(ctx, getDataproductCollection, id)
	var i DataproductCollection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.Repo,
		&i.Created,
		&i.LastModified,
		&i.Team,
		pq.Array(&i.Keywords),
		&i.TsvDocument,
	)
	return i, err
}

const getDataproductCollections = `-- name: GetDataproductCollections :many
SELECT id, name, description, slug, repo, created, last_modified, team, keywords, tsv_document FROM dataproduct_collections ORDER BY last_modified DESC LIMIT $2 OFFSET $1
`

type GetDataproductCollectionsParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) GetDataproductCollections(ctx context.Context, arg GetDataproductCollectionsParams) ([]DataproductCollection, error) {
	rows, err := q.db.QueryContext(ctx, getDataproductCollections, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DataproductCollection{}
	for rows.Next() {
		var i DataproductCollection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Slug,
			&i.Repo,
			&i.Created,
			&i.LastModified,
			&i.Team,
			pq.Array(&i.Keywords),
			&i.TsvDocument,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDataproductCollection = `-- name: UpdateDataproductCollection :one
UPDATE dataproduct_collections SET
	"name" = $1,
	"description" = $2,
	"slug" = $3,
	"repo" = $4,
	"team" = (SELECT team FROM dataproduct_collections dp WHERE dp.id = $5),
	"keywords" = $6
WHERE id = $5
RETURNING id, name, description, slug, repo, created, last_modified, team, keywords, tsv_document
`

type UpdateDataproductCollectionParams struct {
	Name        string
	Description sql.NullString
	Slug        string
	Repo        sql.NullString
	ID          uuid.UUID
	Keywords    []string
}

func (q *Queries) UpdateDataproductCollection(ctx context.Context, arg UpdateDataproductCollectionParams) (DataproductCollection, error) {
	row := q.db.QueryRowContext(ctx, updateDataproductCollection,
		arg.Name,
		arg.Description,
		arg.Slug,
		arg.Repo,
		arg.ID,
		pq.Array(arg.Keywords),
	)
	var i DataproductCollection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.Repo,
		&i.Created,
		&i.LastModified,
		&i.Team,
		pq.Array(&i.Keywords),
		&i.TsvDocument,
	)
	return i, err
}
