// Code generated by sqlc. DO NOT EDIT.
// source: dataproduct_access.sql

package gensql

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteAccessToDataproduct = `-- name: DeleteAccessToDataproduct :exec
UPDATE dataproduct_access 
SET deleted = NOW() 
WHERE id = $1
`

func (q *Queries) DeleteAccessToDataproduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAccessToDataproduct, id)
	return err
}

const grantAccessToDataproduct = `-- name: GrantAccessToDataproduct :one
INSERT INTO dataproduct_access (
	dataproduct_id,
	"subject",
	granter,
	expires
) VALUES (
	$1,
	$2,
	$3,
	$4
)
RETURNING id, dataproduct_id, subject, granter, expires, created, deleted
`

type GrantAccessToDataproductParams struct {
	DataproductID uuid.UUID
	Subject       string
	Granter       string
	Expires       sql.NullTime
}

func (q *Queries) GrantAccessToDataproduct(ctx context.Context, arg GrantAccessToDataproductParams) (DataproductAccess, error) {
	row := q.db.QueryRowContext(ctx, grantAccessToDataproduct,
		arg.DataproductID,
		arg.Subject,
		arg.Granter,
		arg.Expires,
	)
	var i DataproductAccess
	err := row.Scan(
		&i.ID,
		&i.DataproductID,
		&i.Subject,
		&i.Granter,
		&i.Expires,
		&i.Created,
		&i.Deleted,
	)
	return i, err
}

const listAccessToDataproduct = `-- name: ListAccessToDataproduct :many
SELECT id, dataproduct_id, subject, granter, expires, created, deleted FROM dataproduct_access
WHERE dataproduct_id = $1
`

func (q *Queries) ListAccessToDataproduct(ctx context.Context, dataproductID uuid.UUID) ([]DataproductAccess, error) {
	rows, err := q.db.QueryContext(ctx, listAccessToDataproduct, dataproductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DataproductAccess{}
	for rows.Next() {
		var i DataproductAccess
		if err := rows.Scan(
			&i.ID,
			&i.DataproductID,
			&i.Subject,
			&i.Granter,
			&i.Expires,
			&i.Created,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
