// Code generated by sqlc. DO NOT EDIT.

package gensql

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDataproduct(ctx context.Context, arg CreateDataproductParams) (Dataproduct, error)
	CreateDataproductCollection(ctx context.Context, arg CreateDataproductCollectionParams) (DataproductCollection, error)
	CreateDatasourceBigquery(ctx context.Context, arg CreateDatasourceBigqueryParams) (DatasourceBigquery, error)
	DeleteDataproduct(ctx context.Context, id uuid.UUID) error
	DeleteDataproductCollection(ctx context.Context, id uuid.UUID) error
	GetDataproduct(ctx context.Context, id uuid.UUID) (Dataproduct, error)
	GetDataproductCollection(ctx context.Context, id uuid.UUID) (DataproductCollection, error)
	GetDataproductCollections(ctx context.Context, arg GetDataproductCollectionsParams) ([]DataproductCollection, error)
	GetDataproducts(ctx context.Context, arg GetDataproductsParams) ([]Dataproduct, error)
	GetDatasourceBigquery(ctx context.Context, dataproductID uuid.UUID) (DatasourceBigquery, error)
	SearchDataproductCollections(ctx context.Context, arg SearchDataproductCollectionsParams) ([]DataproductCollection, error)
	SearchDataproducts(ctx context.Context, arg SearchDataproductsParams) ([]Dataproduct, error)
	UpdateDataproduct(ctx context.Context, arg UpdateDataproductParams) (Dataproduct, error)
	UpdateDataproductCollection(ctx context.Context, arg UpdateDataproductCollectionParams) (DataproductCollection, error)
	UpdateDatasourceBigquerySchema(ctx context.Context, arg UpdateDatasourceBigquerySchemaParams) error
}

var _ Querier = (*Queries)(nil)
