package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"

	"github.com/navikt/nada-backend/pkg/graph/generated"
	"github.com/navikt/nada-backend/pkg/graph/models"
)

// ProductAreaID is the resolver for the productAreaID field.
func (r *ownerResolver) ProductAreaID(ctx context.Context, obj *models.Owner) (*string, error) {
	if obj.TeamID != nil {
		teamPAMapping, err := r.repo.GetTeamAndProductAreaID(ctx, *obj.TeamID)
		if err != nil {
			return nil, err
		}

		return &teamPAMapping.ProductAreaID.String, nil
	}

	return nil, nil
}

// Owner returns generated.OwnerResolver implementation.
func (r *Resolver) Owner() generated.OwnerResolver { return &ownerResolver{r} }

type ownerResolver struct{ *Resolver }
