package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"fmt"

	"github.com/navikt/nada-backend/pkg/graph/models"
)

// CreatePseudoView is the resolver for the createPseudoView field.
func (r *mutationResolver) CreatePseudoView(ctx context.Context, input models.NewPseudoView) (string, error) {
	pid, did, tid, err := r.bigquery.CreatePseudonymisedView(ctx, input.ProjectID, input.Dataset, input.Table, input.TargetColumns)
	if err != nil {
		r.log.WithError(err).Errorf("failed to create pseudonymised view for %v %v %v", input.ProjectID, input.Dataset, input.Table)
	}
	return fmt.Sprintf("%v.%v.%v", pid, did, tid), err
}

// CreateJoinableViews is the resolver for the createJoinableViews field.
func (r *mutationResolver) CreateJoinableViews(ctx context.Context, input models.NewJoinableViews) (string, error) {
	panic(fmt.Errorf("not implemented: CreateJoinableViews - createJoinableViews"))
}
