package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.25

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/navikt/nada-backend/pkg/auth"
	"github.com/navikt/nada-backend/pkg/graph/models"
)

// CreateQuartoStory is the resolver for the createQuartoStory field.
func (r *mutationResolver) CreateQuartoStory(ctx context.Context, file graphql.Upload, input models.NewQuartoStory) (*models.QuartoStory, error) {
	story, err := r.repo.CreateQuartoStory(ctx, auth.GetUser(ctx).Email, input)
	if err != nil {
		return nil, err
	}

	if err = WriteFileToBucket(ctx, story.ID.String(), file); err != nil {
		return nil, err
	}

	//Create a new File object with the uploaded file's public URL
	return &story, nil
}
