package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
)

// IsValidSlackChannel is the resolver for the IsValidSlackChannel field.
func (r *queryResolver) IsValidSlackChannel(ctx context.Context, name string) (bool, error) {
	return r.slack.IsValidSlackChannel(name)
}
