// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type SearchResultRow struct {
	Excerpt string       `json:"excerpt"`
	Result  SearchResult `json:"result"`
	Rank    float64      `json:"rank"`
}
