// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Group struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UserInfo struct {
	Name   string   `json:"name"`
	Email  string   `json:"email"`
	Groups []*Group `json:"groups"`
}
