oauth:
  client_id: # Loaded from env var
  client_secret: # Loaded from env var
  tenant_id: # Loaded from env var
  redirect_url: http://localhost:8080/api/oauth2/callback
metabase:
  username: metabase
  password: mysecretpassword
  api_url: http://localhost:8083/api
  credentials_path: #FIXME: Figure out how we can re-enable this and use local metabase instance
slack:
  webhook_url: # Loaded from env var
  token: # Loaded from env var
server:
  hostname: localhost
  address: 127.0.0.1
  port: 8080
postgres:
  host: localhost
  port: 5432
  user_name: nada-backend
  password: postgres
  database_name: nada
  ssl_mode: disable
  configuration:
    max_open_connections: 5
    max_idle_connections: 3
teams_catalogue:
  api_url: https://teamkatalog-api.intern.nav.no
treatment_catalogue:
  api_url: https://polly.intern.dev.nav.no/process
google_groups:
  impersonation_subject: johnny.horvi@nav.no
  credentials_file: ./test-sa.json
gcp:
  project: datamarkedsplassen-dev
  region: europe-north1
  gcs:
    story_bucket_name: nada-quarto-storage-dev
  big_query:
    pseudo_views_dataset_name: markedsplassen_pseudo
cookies:
  redirect:
    name: redirecturi
    max_age: 3600
    path: /
    domain: localhost
    same_site: Lax
    secure: false
    http_only: true
  oauth_state:
    name: oauthstate
    max_age: 3600
    path: /
    domain: localhost
    same_site: Lax
    secure: false
    http_only: true
  session:
    name: nada_session
    max_age: 86400
    path: /
    domain: localhost
    same_site: Lax
    secure: false
    http_only: true
nais_console:
  api_key: # Loaded from env var
  api_url: https://console.nav.cloud.nais.io
api:
  auth_token: 1234
login_page: http://localhost:3000/
amplitude_api_key: # Loaded from env var
skip_metadata_sync: true
mock_auth: true
debug: false
log_level: debug
