version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nada
    command: ["postgres", "-c", "log_statement=all", "-c", "wal_level=logical"]
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  gcs:
    image: fsouza/fake-gcs-server:1.44
    restart: always
    ports:
      - 8082:4443
    entrypoint: ["/bin/sh", "-c", "mkdir -p /storage/nada-quarto-storage-dev && /bin/fake-gcs-server -scheme http -public-host localhost:8082"]
