openapi: 3.0.2
info:
  title: API Title
  version: "1.0"
servers:
  - url: "https://api.server.test/api"

components:
  schemas:
    Dataproduct:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        slug:
          type: string
        repo:
          type: string
        last_modified:
          type: string
          format: date-time
        created:
          type: string
          format: date-time
        owner:
          $ref: "#/components/schemas/Owner"
        keywords:
          type: array
          items:
            type: string
        datasets:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              type:
                $ref: "#/components/schemas/DatasetType"
      required:
        - id
        - name
        - slug
        - owner
        - created
        - last_modified

    DatasetType:
      type: string
      enum:
        - bigquery

    Owner:
      type: object
      properties:
        team:
          type: string
        teamkatalogen:
          type: string
      required:
        - team

    BigQuery:
      type: object
      properties:
        project_id:
          type: string
        dataset:
          type: string
        table:
          type: string
      required:
        - project_id
        - dataset
        - table

    NewDataproduct:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        slug:
          type: string
        repo:
          type: string
        owner:
          $ref: "#/components/schemas/Owner"
        keywords:
          type: array
          items:
            type: string
      required:
        - name
        - owner

    Dataset:
      type: object
      properties:
        id:
          type: string
        dataproduct_id:
          type: string
        name:
          type: string
        description:
          type: string
        pii:
          type: boolean
        bigquery:
          $ref: "#/components/schemas/BigQuery"
      required:
        - id
        - name
        - pii
        - dataproduct_id
        - bigquery

    NewDataset:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        pii:
          type: boolean
        bigquery:
          $ref: "#/components/schemas/BigQuery"
      required:
        - name
        - pii
        - bigquery # Update this to a oneOf when we have more than bigquery


    SearchResultEntry:
      type: object
      properties:
        url:
          type: string
        type:
          type: string
          enum:
            - dataset
            - dataproduct
            - datapackage
        id:
          type: string
        name:
          type: string
        excerpt:
          type: string

paths:
  /dataproducts:
    get:
      description: "List all dataproducts"
      operationId: "getDataproducts"
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Dataproduct"
    post:
      description: "Create a new dataproduct"
      operationId: "createDataproduct"
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/NewDataproduct"
      responses:
        "201":
          description: "Created successfully"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Dataproduct"

  /dataproducts/{dataproduct_id}:
    get:
      description: "List a dataproduct with datasets"
      operationId: "getDataproduct"
      parameters:
        - in: path
          name: dataproduct_id
          description: Dataproduct ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Dataproduct"
    delete:
      description: "Delete a dataproduct"
      operationId: "deleteDataproduct"
      parameters:
        - in: path
          name: dataproduct_id
          description: Dataproduct ID
          required: true
          schema:
            type: string
      responses:
        "204":
          description: "Deleted OK"
    put:
      description: "Update a dataproduct"
      operationId: "updateDataproduct"
      parameters:
        - in: path
          name: dataproduct_id
          description: Dataproduct ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/NewDataproduct"
      responses:
        "200":
          description: "Updated OK"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Dataproduct"

  /dataproducts/{dataproduct_id}/datasets:
    get:
      description: "List all datasets for a dataproduct"
      operationId: "getDatasetsForDataproduct"
      parameters:
        - in: path
          name: dataproduct_id
          description: Dataproduct ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Dataset"
    post:
      description: "Create a new dataset"
      operationId: "createDataset"
      parameters:
        - in: path
          name: dataproduct_id
          description: Dataproduct ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/NewDataset"
      responses:
        "201":
          description: "Created successfully"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Dataset"

  /dataproducts/{dataproduct_id}/datasets/{dataset_id}:
    get:
      description: "Get dataset"
      operationId: "getDataset"
      parameters:
        - in: path
          name: dataproduct_id
          description: Dataproduct ID
          required: true
          schema:
            type: string
        - in: path
          name: dataset_id
          description: Dataset ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Dataset"
    put:
      description: "Update a dataset"
      operationId: "updateDataset"
      parameters:
        - in: path
          name: dataproduct_id
          description: Dataproduct ID
          required: true
          schema:
            type: string
        - in: path
          name: dataset_id
          description: Dataset ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/NewDataset"
      responses:
        "200":
          description: "Updated OK"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Dataset"
    delete:
      description: "Delete a dataset"
      operationId: "deleteDataset"
      parameters:
        - in: path
          name: dataproduct_id
          description: Dataproduct ID
          required: true
          schema:
            type: string
        - in: path
          name: dataset_id
          description: Dataset ID
          required: true
          schema:
            type: string
      responses:
        "204":
          description: "Deleted OK"
  /search:
    parameters:
      - in: query
        name: q
        schema:
          type: string
    get:
      description: "Search in Datakatalog"
      operationId: "search"
      responses:
        "200":
          description: Search result
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SearchResultEntry"
