openapi: 3.0.2
info:
  title: API Title
  version: "1.0"
servers:
  - url: "https://api.server.test/api"

components:
  securitySchemes:
    cookieAuth:
      type: token
      in: cookie
      name: jwt
  schemas:
    Dataproduct:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        slug:
          type: string
        repo:
          type: string
        last_modified:
          type: string
          format: date-time
        created:
          type: string
          format: date-time
        owner:
          $ref: "#/components/schemas/Owner"
        keywords:
          type: array
          items:
            type: string
        datasets:
          type: array
          items:
            $ref: "#/components/schemas/DatasetSummary"
      required:
        - id
        - name
        - slug
        - owner
        - created
        - last_modified
        - datasets

    DatasetSummary:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        type:
          $ref: "#/components/schemas/DatasetType"
      required:
        - id
        - name
        - type

    DatasetType:
      type: string
      enum:
        - bigquery

    Owner:
      type: object
      properties:
        team:
          type: string
        teamkatalogen:
          type: string
      required:
        - team

    BigQuery:
      type: object
      properties:
        project_id:
          type: string
        dataset:
          type: string
        table:
          type: string
      required:
        - project_id
        - dataset
        - table

    NewDataproduct:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        slug:
          type: string
        repo:
          type: string
        owner:
          $ref: "#/components/schemas/Owner"
        keywords:
          type: array
          items:
            type: string
      required:
        - name
        - owner

    UserInfo:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        teams:
          type: array
          items:
            type: string

    Dataset:
      type: object
      properties:
        id:
          type: string
        dataproduct_id:
          type: string
        name:
          type: string
        description:
          type: string
        pii:
          type: boolean
        bigquery:
          $ref: "#/components/schemas/BigQuery"
      required:
        - id
        - name
        - pii
        - dataproduct_id
        - bigquery

    NewDataset:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        dataproduct_id:
          type: string
        pii:
          type: boolean
        bigquery:
          $ref: "#/components/schemas/BigQuery"
      required:
        - name
        - dataproduct_id
        - pii
        - bigquery # Update this to a oneOf when we have more than bigquery

    SearchResultEntry:
      type: object
      properties:
        url:
          type: string
        type:
          $ref: "#/components/schemas/SearchResultType"
        id:
          type: string
        name:
          type: string
        excerpt:
          type: string
      required:
        - url
        - type
        - id
        - name
        - excerpt

    SearchResultType:
      type: string
      enum:
        - dataset
        - dataproduct
        - datapackage

paths:
  /userinfo:
    get:
      security:
        - cookieAuth: []
      description: "get user info"
      operationId: "getUserInfo"
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/UserInfo"

  /dataproducts:
    get:
      description: "List all dataproducts"
      operationId: "getDataproducts"
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Dataproduct"
    post:
      security:
        - cookieAuth: []
      description: "Create a new dataproduct"
      operationId: "createDataproduct"
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/NewDataproduct"
      responses:
        "201":
          description: "Created successfully"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Dataproduct"

  /dataproducts/{id}:
    get:
      description: "List a dataproduct with datasets"
      operationId: "getDataproduct"
      parameters:
        - in: path
          name: id
          description: Dataproduct ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Dataproduct"
    delete:
      security:
        - cookieAuth: []
      description: "Delete a dataproduct"
      operationId: "deleteDataproduct"
      parameters:
        - in: path
          name: id
          description: Dataproduct ID
          required: true
          schema:
            type: string
      responses:
        "204":
          description: "Deleted OK"
    put:
      security:
        - cookieAuth: []
      description: "Update a dataproduct"
      operationId: "updateDataproduct"
      parameters:
        - in: path
          name: id
          description: Dataproduct ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/NewDataproduct"
      responses:
        "200":
          description: "Updated OK"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Dataproduct"
  
  /datasets:
    post:
      security:
        - cookieAuth: []
      description: "Create a new dataset"
      operationId: "createDataset"
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/NewDataset"
      responses:
        "201":
          description: "Created successfully"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Dataset"

  /datasets/{id}:
    get:
      description: "Get dataset"
      operationId: "getDataset"
      parameters:
        - in: path
          name: id
          description: Dataset ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Dataset"
    put:
      security:
        - cookieAuth: []
      description: "Update a dataset"
      operationId: "updateDataset"
      parameters:
        - in: path
          name: id
          description: Dataset ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/NewDataset"
      responses:
        "200":
          description: "Updated OK"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Dataset"
    delete:
      security:
        - cookieAuth: []
      description: "Delete a dataset"
      operationId: "deleteDataset"
      parameters:
        - in: path
          name: id
          description: Dataset ID
          required: true
          schema:
            type: string
      responses:
        "204":
          description: "Deleted OK"
  /search:
    parameters:
      - in: query
        required: true
        name: q
        schema:
          type: string

    get:
      description: "Search in NADA"
      operationId: "search"
      responses:
        "200":
          description: Search result
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SearchResultEntry"
