apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: nada-backend
  namespace: dataplattform
  labels:
    team: dataplattform
spec:
  image: {{ image }}
  port: 8080
  azure:
    application:
      enabled: true
      tenant: nav.no
      replyURLs:
        - "http://localhost:8080/api/oauth2/callback"
        - "https://nada.dev.intern.nav.no/api/oauth2/callback"
  ingresses:
    - "https://nada.dev.intern.nav.no/api"
  env:
    - name: HOSTNAME
      value: "nada.dev.intern.nav.no"
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: nada
