kind: "Application"
apiVersion: "nais.io/v1alpha1"
metadata:
  name: nada-backend
  namespace: nada
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
  labels:
    team: nada
spec:
  image: "{{ image }}"
  port: 8080
  azure:
    application:
      enabled: true
      replyURLs:
        - https://data.intern.dev.nav.no/api/oauth2/callback
        - http://localhost:8080/api/oauth2/callback
      tenant: nav.no
      allowAllUsers: true
  command:
    - /app/nada-backend
    - --teamkatalogen-url
    - https://teamkatalog-api.dev-fss-pub.nais.io
    - --polly-url
    - https://polly.dev-fss-pub.nais.io/process
    - --team-projects-url
    - https://raw.githubusercontent.com/nais/teams/master/gcp-projects/dev-output.json
  replicas:
    min: 2
    max: 4
  leaderElection: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: /internal/metrics
  ingresses:
    - "https://data.intern.dev.nav.no/api"
    - "https://data.intern.dev.nav.no/quarto"
    - "https://nada.ekstern.dev.nav.no/api"
    - "https://nada.intern.dev.nav.no/quarto/update"
  envFrom:
    - secret: nada-backend
  filesFrom:
    - secret: nada-backend-google-credentials
      mountPath: /var/run/secrets/google-credentials
    - secret: nada-backend-metabase-sa
      mountPath: /var/run/secrets/nada-credentials
  env:
    - name: GOOGLE_ADMIN_CREDENTIALS_PATH
      value: /var/run/secrets/google-credentials/sa.json
    - name: HOSTNAME
      value: "data.intern.dev.nav.no"
    - name: METABASE_API
      value: "http://metabase/api"
    - name: METABASE_GOOGLE_CREDENTIALS_PATH
      value: /var/run/secrets/nada-credentials/meta_creds.json
    - name: DASHBOARD_PA_ID
      value: deab2907-c8ac-4db9-b997-328cce77d797
    - name: GCP_QUARTO_STORAGE_BUCKET_NAME
      value: nada-quarto-storage-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: nada
            users:
              - name: datastream
        flags:
          - name: max_connections
            value: "50"
          - name: cloudsql.logical_decoding
            value: "on"
    buckets:
      - name: nada-quarto-storage-dev
        publicAccessPrevention: true
        uniformBucketLevelAccess: true
  accessPolicy:
    inbound:
      rules:
        - application: nada-frontend
        - application: nada-datasetenricher
        - application: metrics-markedsplassen
    outbound:
      rules:
        - application: metabase
      external:
        - host: teamkatalog-api.dev-fss-pub.nais.io
        - host: teams.nav.cloud.nais.io
