kind: "Application"
apiVersion: "nais.io/v1alpha1"
metadata:
  name: nada-backend
  namespace: nada
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
  labels:
    team: nada
spec:
  image: "{{ image }}"
  port: 8080
  command:
    - /app/nada-backend
    - --teamkatalogen-url
    - https://teamkatalog-api.dev-fss-pub.nais.io/team
  replicas:
    min: 2
    max: 4
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: /internal/metrics
  ingresses:
    - "https://data.dev.intern.nav.no/api"
    - "https://nada.ekstern.dev.nav.no/api"
    - "https://data.dev.intern.nav.no/datapakke/"
  envFrom:
    - secret: impersonation-subject
    - secret: github-read-token
    - secret: google-oauth
    - secret: slack
  filesFrom:
    - secret: google-credentials
      mountPath: /var/run/secrets/google-credentials
  env:
    - name: GOOGLE_ADMIN_CREDENTIALS_PATH
      value: /var/run/secrets/google-credentials/sa.json
    - name: HOSTNAME
      value: "data.dev.intern.nav.no"
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: nada
  accessPolicy:
    inbound:
      rules:
        - application: nada-frontend
    outbound:
      rules:
        - application: metabase
