kind: "Application"
apiVersion: "nais.io/v1alpha1"
metadata:
  name: nada-backend
  namespace: nada
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
  labels:
    team: nada
spec:
  image: "{{ image }}"
  port: 8080
  azure:
    application:
      enabled: true
      replyURLs:
        - https://data.intern.nav.no/api/oauth2/callback
      tenant: nav.no
      allowAllUsers: true
  replicas:
    min: 2
    max: 4
  leaderElection: true
  resources:
    requests:
      cpu: 50m
      memory: 200Mi
    limits:
      memory: 512Mi
  prometheus:
    enabled: true
    path: /internal/metrics
  ingresses:
    - "https://data.intern.nav.no/quarto"
    - "https://data.intern.nav.no/api"
    - "https://nada.intern.nav.no/quarto/update"
    - "https://nada.intern.nav.no/api/story"
    - "https://datamarkedsplassen.intern.nav.no/quarto/create"
    - "https://datamarkedsplassen.intern.nav.no/quarto/update"
    - "https://datamarkedsplassen.intern.nav.no/api/story"
    - "https://data.nav.no/quarto/create"
    - "https://data.nav.no/quarto/update"
    - "https://data.nav.no/api/story"
  envFrom:
    - secret: nada-backend
  filesFrom:
    - secret: nada-backend-google-credentials
      mountPath: /var/run/secrets/google-credentials
    - secret: nada-backend-metabase-sa
      mountPath: /var/run/secrets/nada-credentials
  env:
    - name: GOOGLE_ADMIN_CREDENTIALS_PATH
      value: /var/run/secrets/google-credentials/sa.json
    - name: HOSTNAME
      value: "data.intern.nav.no"
    - name: METABASE_API
      value: "http://metabase/api"
    - name: METABASE_GOOGLE_CREDENTIALS_PATH
      value: /var/run/secrets/nada-credentials/meta_creds.json
    - name: DASHBOARD_PA_ID
      value: 6b149078-927b-4570-a1ce-97bbb9499fb6
    - name: GCP_QUARTO_STORAGE_BUCKET_NAME
      value: nada-quarto-storage-prod
    - name: CENTRAL_DATA_PROJECT
      value: datamarkedsplassen
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: nada
            users:
              - name: datastream
        flags:
          - name: max_connections
            value: "50"
          - name: cloudsql.logical_decoding
            value: "on"
        diskAutoresize: true
    buckets:
      - name: nada-quarto-storage-prod
        publicAccessPrevention: true
        uniformBucketLevelAccess: true

  accessPolicy:
    inbound:
      rules:
        - application: nada-frontend
        - application: nada-datasetenricher
        - application: metrics-markedsplassen
    outbound:
      rules:
        - application: metabase
        - application: team-catalog-backend
          namespace: org
        - application: behandlingskatalog-backend
          namespace: teamdatajegerne
      external:
        - host: teams.nav.cloud.nais.io
        - host: amplitude.nav.no
        - host: slack.com

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nada-backend-alert
  namespace: nada
  labels:
    team: nada
spec:
  groups:
  - name: nada-backend-alert
    rules:
    - alert: InstanceDown
      expr: kube_deployment_status_replicas_available{namespace="nada", deployment="nada-backend"} == 0
      for: 2m
      annotations:
        consequence: Nada backend is unavailable
        action: "`kubectl describe pod <podname>` -> `kubectl logs <podname>`"
        summary: |-
          No nada-backend pods are running in prod-gcp
      labels:
        namespace: nada
        severity: critical
    - alert: ErrorInLogs
      expr: sum(increase(log_messages_errors{container="nada-backend"}[10m])) > 0
      for: 5m
      annotations:
        consequence: Enten feil i kode, eller en state vi ikke kjenner til.
        action: |-
          Backend til Datamarkedsplassen logger error, sjekk loggene og finn feilen.
          Logs: https://logs.adeo.no/app/r/s/7EIEB
        summary: Vurder også om det er verdt å logge error ved denne type feil.
      labels:
        namespace: nada
        severity: critical
