kind: "Application"
apiVersion: "nais.io/v1alpha1"
metadata:
  name: nada-backend
  namespace: nada
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
  labels:
    team: nada
spec:
  image: "{{ image }}"
  port: 8080
  azure:
    application:
      enabled: true
      replyURLs:
        - https://data.ansatt.nav.no/api/oauth2/callback
      tenant: nav.no
      allowAllUsers: true
  replicas:
    min: 2
    max: 4
  leaderElection: true
  resources:
    requests:
      cpu: 20m
      memory: 200Mi
    limits:
      memory: 300Mi
  prometheus:
    enabled: true
    path: /internal/metrics
  ingresses:
    - "https://data.ansatt.nav.no/api"
    - "https://data.ansatt.nav.no/story"
    - "https://data.ansatt.nav.no/quarto"
    - "https://nada.intern.nav.no/quarto/update"
    - "https://nada.intern.nav.no/api/story"
    - "https://datamarkedsplassen.intern.nav.no/quarto/create"
    - "https://datamarkedsplassen.intern.nav.no/quarto/update"
    - "https://datamarkedsplassen.intern.nav.no/api/story"
    - "https://data.nav.no/quarto/create"
    - "https://data.nav.no/quarto/update"
  envFrom:
    - secret: nada-backend
  filesFrom:
    - secret: nada-backend-google-credentials
      mountPath: /var/run/secrets/google-credentials
    - secret: nada-backend-metabase-sa
      mountPath: /var/run/secrets/nada-credentials
  env:
    - name: GOOGLE_ADMIN_CREDENTIALS_PATH
      value: /var/run/secrets/google-credentials/sa.json
    - name: HOSTNAME
      value: "data.ansatt.nav.no"
    - name: METABASE_API
      value: "http://metabase/api"
    - name: METABASE_GOOGLE_CREDENTIALS_PATH
      value: /var/run/secrets/nada-credentials/meta_creds.json
    - name: DASHBOARD_PA_ID
      value: 6b149078-927b-4570-a1ce-97bbb9499fb6
    - name: GCP_STORY_BUCKET_NAME
      value: nada-quarto-storage-prod
    - name: CENTRAL_DATA_PROJECT
      value: datamarkedsplassen
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: nada
            users:
              - name: datastream
        flags:
          - name: max_connections
            value: "50"
          - name: cloudsql.logical_decoding
            value: "on"
        diskAutoresize: true
    buckets:
      - name: nada-quarto-storage-prod
        publicAccessPrevention: true
        uniformBucketLevelAccess: true

  accessPolicy:
    inbound:
      rules:
        - application: nada-frontend
        - application: nada-datasetenricher
        - application: metrics-markedsplassen
        - application: story-api
    outbound:
      rules:
        - application: metabase
        - application: team-catalog-backend
          namespace: org
        - application: behandlingskatalog-backend
          namespace: teamdatajegerne
      external:
        - host: console.nav.cloud.nais.io
        - host: amplitude.nav.no
        - host: slack.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      return 301 https://data.ansatt.nav.no$request_uri;
  labels:
    team: nada
  name: dmp-redirect
  namespace: nada
spec:
  ingressClassName: nais-ingress
  rules:
  - host: data.intern.nav.no
