// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for DatasetType.
const (
	DatasetTypeBigquery DatasetType = "bigquery"
)

// Defines values for SearchResultEntryType.
const (
	SearchResultEntryTypeDatapackage SearchResultEntryType = "datapackage"

	SearchResultEntryTypeDataproduct SearchResultEntryType = "dataproduct"

	SearchResultEntryTypeDataset SearchResultEntryType = "dataset"
)

// BigQuery defines model for BigQuery.
type BigQuery struct {
	Dataset   string `json:"dataset"`
	ProjectId string `json:"project_id"`
	Table     string `json:"table"`
}

// Dataproduct defines model for Dataproduct.
type Dataproduct struct {
	Created      time.Time        `json:"created"`
	Datasets     []DatasetSummary `json:"datasets"`
	Description  *string          `json:"description,omitempty"`
	Id           string           `json:"id"`
	Keywords     *[]string        `json:"keywords,omitempty"`
	LastModified time.Time        `json:"last_modified"`
	Name         string           `json:"name"`
	Owner        Owner            `json:"owner"`
	Repo         *string          `json:"repo,omitempty"`
	Slug         string           `json:"slug"`
}

// Dataset defines model for Dataset.
type Dataset struct {
	Bigquery      BigQuery `json:"bigquery"`
	DataproductId string   `json:"dataproduct_id"`
	Description   *string  `json:"description,omitempty"`
	Id            string   `json:"id"`
	Name          string   `json:"name"`
	Pii           bool     `json:"pii"`
}

// DatasetSummary defines model for DatasetSummary.
type DatasetSummary struct {
	Id   string      `json:"id"`
	Name string      `json:"name"`
	Type DatasetType `json:"type"`
}

// DatasetType defines model for DatasetType.
type DatasetType string

// NewDataproduct defines model for NewDataproduct.
type NewDataproduct struct {
	Description *string   `json:"description,omitempty"`
	Keywords    *[]string `json:"keywords,omitempty"`
	Name        string    `json:"name"`
	Owner       Owner     `json:"owner"`
	Repo        *string   `json:"repo,omitempty"`
	Slug        *string   `json:"slug,omitempty"`
}

// NewDataset defines model for NewDataset.
type NewDataset struct {
	Bigquery      BigQuery `json:"bigquery"`
	DataproductId string   `json:"dataproduct_id"`
	Description   *string  `json:"description,omitempty"`
	Name          string   `json:"name"`
	Pii           bool     `json:"pii"`
}

// Owner defines model for Owner.
type Owner struct {
	Team          string  `json:"team"`
	Teamkatalogen *string `json:"teamkatalogen,omitempty"`
}

// SearchResultEntry defines model for SearchResultEntry.
type SearchResultEntry struct {
	Excerpt *string                `json:"excerpt,omitempty"`
	Id      *string                `json:"id,omitempty"`
	Name    *string                `json:"name,omitempty"`
	Type    *SearchResultEntryType `json:"type,omitempty"`
	Url     *string                `json:"url,omitempty"`
}

// SearchResultEntryType defines model for SearchResultEntry.Type.
type SearchResultEntryType string

// CreateDataproductJSONBody defines parameters for CreateDataproduct.
type CreateDataproductJSONBody NewDataproduct

// UpdateDataproductJSONBody defines parameters for UpdateDataproduct.
type UpdateDataproductJSONBody NewDataproduct

// CreateDatasetJSONBody defines parameters for CreateDataset.
type CreateDatasetJSONBody NewDataset

// UpdateDatasetJSONBody defines parameters for UpdateDataset.
type UpdateDatasetJSONBody NewDataset

// SearchParams defines parameters for Search.
type SearchParams struct {
	Q *string `json:"q,omitempty"`
}

// CreateDataproductJSONRequestBody defines body for CreateDataproduct for application/json ContentType.
type CreateDataproductJSONRequestBody CreateDataproductJSONBody

// UpdateDataproductJSONRequestBody defines body for UpdateDataproduct for application/json ContentType.
type UpdateDataproductJSONRequestBody UpdateDataproductJSONBody

// CreateDatasetJSONRequestBody defines body for CreateDataset for application/json ContentType.
type CreateDatasetJSONRequestBody CreateDatasetJSONBody

// UpdateDatasetJSONRequestBody defines body for UpdateDataset for application/json ContentType.
type UpdateDatasetJSONRequestBody UpdateDatasetJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /dataproducts)
	GetDataproducts(w http.ResponseWriter, r *http.Request)

	// (POST /dataproducts)
	CreateDataproduct(w http.ResponseWriter, r *http.Request)

	// (DELETE /dataproducts/{id})
	DeleteDataproduct(w http.ResponseWriter, r *http.Request, id string)

	// (GET /dataproducts/{id})
	GetDataproduct(w http.ResponseWriter, r *http.Request, id string)

	// (PUT /dataproducts/{id})
	UpdateDataproduct(w http.ResponseWriter, r *http.Request, id string)

	// (POST /datasets)
	CreateDataset(w http.ResponseWriter, r *http.Request)

	// (DELETE /datasets/{id})
	DeleteDataset(w http.ResponseWriter, r *http.Request, id string)

	// (GET /datasets/{id})
	GetDataset(w http.ResponseWriter, r *http.Request, id string)

	// (PUT /datasets/{id})
	UpdateDataset(w http.ResponseWriter, r *http.Request, id string)

	// (GET /search)
	Search(w http.ResponseWriter, r *http.Request, params SearchParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// GetDataproducts operation middleware
func (siw *ServerInterfaceWrapper) GetDataproducts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDataproducts(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// CreateDataproduct operation middleware
func (siw *ServerInterfaceWrapper) CreateDataproduct(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDataproduct(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// DeleteDataproduct operation middleware
func (siw *ServerInterfaceWrapper) DeleteDataproduct(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDataproduct(w, r, id)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetDataproduct operation middleware
func (siw *ServerInterfaceWrapper) GetDataproduct(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDataproduct(w, r, id)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UpdateDataproduct operation middleware
func (siw *ServerInterfaceWrapper) UpdateDataproduct(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateDataproduct(w, r, id)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// CreateDataset operation middleware
func (siw *ServerInterfaceWrapper) CreateDataset(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDataset(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// DeleteDataset operation middleware
func (siw *ServerInterfaceWrapper) DeleteDataset(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDataset(w, r, id)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetDataset operation middleware
func (siw *ServerInterfaceWrapper) GetDataset(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDataset(w, r, id)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UpdateDataset operation middleware
func (siw *ServerInterfaceWrapper) UpdateDataset(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateDataset(w, r, id)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Search operation middleware
func (siw *ServerInterfaceWrapper) Search(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchParams

	// ------------- Optional query parameter "q" -------------
	if paramValue := r.URL.Query().Get("q"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter q: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Search(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL     string
	BaseRouter  chi.Router
	Middlewares []MiddlewareFunc
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dataproducts", wrapper.GetDataproducts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dataproducts", wrapper.CreateDataproduct)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/dataproducts/{id}", wrapper.DeleteDataproduct)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dataproducts/{id}", wrapper.GetDataproduct)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/dataproducts/{id}", wrapper.UpdateDataproduct)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/datasets", wrapper.CreateDataset)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/datasets/{id}", wrapper.DeleteDataset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/datasets/{id}", wrapper.GetDataset)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/datasets/{id}", wrapper.UpdateDataset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/search", wrapper.Search)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xXTY/bNhD9KwLbo2o7aU+6NXURLFp022Z7ChbBrDS2mZVILjmKayz83wt+yLIkSl6n",
	"ieObRA5nOG/eG5LPLJeVkgIFGZY9M5NvsAL3+Yav/6pR7+y30lKhJo5upgACg2Q/aaeQZcyQ5mLN9qm1",
	"/Ig5feBFdJrgocTIzD5lGp9qrrFg2ftjL+khXLP6Pm1WywdrZf0ugUBpWdQ5DfebawRCt6GV1BUQy6xT",
	"/IF4hSwd7jJEdIs5YeU+vte4Yhn7bt4iNg9wzZd+wbu6qkDvXKLeJ2gN7r9Ak2uuiEsRBWYEr0fcbaUu",
	"ujsZotoLVoKhD5Us+Iqfk7aACqP+5VagPoXBrTNyhVQy6saU9fp07V3N3VbCiiZ+eihkP8Ojio2RI/C1",
	"S4wHvn5qKD6V2kEKgRuBaWMk/8xaj8KvOD8af5CyRBCTuNkVg62mbb4TKDUcHoB17q79wIt0c2dNp/Jx",
	"viY2fRdioagruzaSaLuxP3A72S5Ole/zNHkd4gp4+pgxQAM41ySX/6mLkPJADF4jk5K4bUrTxYEQqnjN",
	"EapHICjlGsXpYjg/sbjvEHS++RtNXdKvgmJqxH9z1Iq+SH+hnnraA/cItOYP8kdYY1RYtS7jSfcStENc",
	"rDyPOdkLAfv5z5vkzn2n7BNq48jAXs0WTiIKBSjOMvbjbDF7bYsHtHE4zI+26AbWnrkdUrHfuaEEyjLp",
	"WDvHGqzNTcEy9hZp2Z3XaJQUxkP+erFwtwkpCIULAkqVPHcO5h+Np68XwVk3hwbhQdfY99XBbn/zo0qa",
	"SJq/uPMxgUTgNunWrpupN1x2LCwz0dAbWezOSnMqu16r3e+9BDqgvvpi0Xqh0ig6RWLqPEdjVnVZ7sKW",
	"OiyaP/Ni78EtkXAI89KNJzAJsTfqQqxAQ4WE2rDs/cBra5rcLJmVCMsc0ZtzMPNnYttCSNeYHoHTV979",
	"AOyfxrIpkoZaEwI6TjjZctokh3vXtJauIvcrUm8dgfgfVcBJVnmjK0D22/SKxaV6hce5EUXTIZo34Qu7",
	"rz9Dxzqvn/2KSNoAF+i4Icy53dZieV6njcHZdlk/e1ILBq+wu75FGs0wNNJrSG9xCd68vEfG0Gr74zcC",
	"7PJqvkhVhv3QuDfK6I3bP2ESLhLrNTyKBuXyVhe5aA/fVC84sEMW2q0KvOwyytHGvyAPvHlikzSxXgzq",
	"T40L92xiGyJlsvkcFJ/52RmhIfvP9vf7/wIAAP//2KpZCqkVAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

