// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.2 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for DatasetType.
const (
	DatasetTypeBigquery DatasetType = "bigquery"
)

// Defines values for SearchResultType.
const (
	SearchResultTypeDatapackage SearchResultType = "datapackage"

	SearchResultTypeDataproduct SearchResultType = "dataproduct"

	SearchResultTypeDataset SearchResultType = "dataset"
)

// BigQuery defines model for BigQuery.
type BigQuery struct {
	Dataset   string `json:"dataset"`
	ProjectId string `json:"project_id"`
	Table     string `json:"table"`
}

// Dataproduct defines model for Dataproduct.
type Dataproduct struct {
	Created      time.Time        `json:"created"`
	Datasets     []DatasetSummary `json:"datasets"`
	Description  *string          `json:"description,omitempty"`
	Id           string           `json:"id"`
	Keywords     *[]string        `json:"keywords,omitempty"`
	LastModified time.Time        `json:"last_modified"`
	Name         string           `json:"name"`
	Owner        Owner            `json:"owner"`
	Repo         *string          `json:"repo,omitempty"`
	Slug         string           `json:"slug"`
}

// Dataset defines model for Dataset.
type Dataset struct {
	Bigquery      BigQuery `json:"bigquery"`
	DataproductId string   `json:"dataproduct_id"`
	Description   *string  `json:"description,omitempty"`
	Id            string   `json:"id"`
	Name          string   `json:"name"`
	Pii           bool     `json:"pii"`
}

// DatasetSummary defines model for DatasetSummary.
type DatasetSummary struct {
	Id   string      `json:"id"`
	Name string      `json:"name"`
	Type DatasetType `json:"type"`
}

// DatasetType defines model for DatasetType.
type DatasetType string

// NewDataproduct defines model for NewDataproduct.
type NewDataproduct struct {
	Description *string   `json:"description,omitempty"`
	Keywords    *[]string `json:"keywords,omitempty"`
	Name        string    `json:"name"`
	Owner       Owner     `json:"owner"`
	Repo        *string   `json:"repo,omitempty"`
	Slug        *string   `json:"slug,omitempty"`
}

// NewDataset defines model for NewDataset.
type NewDataset struct {
	Bigquery      BigQuery `json:"bigquery"`
	DataproductId string   `json:"dataproduct_id"`
	Description   *string  `json:"description,omitempty"`
	Name          string   `json:"name"`
	Pii           bool     `json:"pii"`
}

// Owner defines model for Owner.
type Owner struct {
	Team          string  `json:"team"`
	Teamkatalogen *string `json:"teamkatalogen,omitempty"`
}

// SearchResultEntry defines model for SearchResultEntry.
type SearchResultEntry struct {
	Excerpt string           `json:"excerpt"`
	Id      string           `json:"id"`
	Name    string           `json:"name"`
	Type    SearchResultType `json:"type"`
	Url     string           `json:"url"`
}

// SearchResultType defines model for SearchResultType.
type SearchResultType string

// UserInfo defines model for UserInfo.
type UserInfo struct {
	Email string   `json:"email"`
	Name  string   `json:"name"`
	Teams []string `json:"teams"`
}

// GetDataproductsParams defines parameters for GetDataproducts.
type GetDataproductsParams struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

// CreateDataproductJSONBody defines parameters for CreateDataproduct.
type CreateDataproductJSONBody NewDataproduct

// UpdateDataproductJSONBody defines parameters for UpdateDataproduct.
type UpdateDataproductJSONBody NewDataproduct

// CreateDatasetJSONBody defines parameters for CreateDataset.
type CreateDatasetJSONBody NewDataset

// UpdateDatasetJSONBody defines parameters for UpdateDataset.
type UpdateDatasetJSONBody NewDataset

// SearchParams defines parameters for Search.
type SearchParams struct {
	Q      *string `json:"q,omitempty"`
	Limit  *int    `json:"limit,omitempty"`
	Offset *int    `json:"offset,omitempty"`
}

// CreateDataproductJSONRequestBody defines body for CreateDataproduct for application/json ContentType.
type CreateDataproductJSONRequestBody CreateDataproductJSONBody

// UpdateDataproductJSONRequestBody defines body for UpdateDataproduct for application/json ContentType.
type UpdateDataproductJSONRequestBody UpdateDataproductJSONBody

// CreateDatasetJSONRequestBody defines body for CreateDataset for application/json ContentType.
type CreateDatasetJSONRequestBody CreateDatasetJSONBody

// UpdateDatasetJSONRequestBody defines body for UpdateDataset for application/json ContentType.
type UpdateDatasetJSONRequestBody UpdateDatasetJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /dataproducts)
	GetDataproducts(w http.ResponseWriter, r *http.Request, params GetDataproductsParams)

	// (POST /dataproducts)
	CreateDataproduct(w http.ResponseWriter, r *http.Request)

	// (DELETE /dataproducts/{id})
	DeleteDataproduct(w http.ResponseWriter, r *http.Request, id string)

	// (GET /dataproducts/{id})
	GetDataproduct(w http.ResponseWriter, r *http.Request, id string)

	// (PUT /dataproducts/{id})
	UpdateDataproduct(w http.ResponseWriter, r *http.Request, id string)

	// (POST /datasets)
	CreateDataset(w http.ResponseWriter, r *http.Request)

	// (DELETE /datasets/{id})
	DeleteDataset(w http.ResponseWriter, r *http.Request, id string)

	// (GET /datasets/{id})
	GetDataset(w http.ResponseWriter, r *http.Request, id string)

	// (PUT /datasets/{id})
	UpdateDataset(w http.ResponseWriter, r *http.Request, id string)

	// (GET /search)
	Search(w http.ResponseWriter, r *http.Request, params SearchParams)

	// (GET /userinfo)
	GetUserInfo(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// GetDataproducts operation middleware
func (siw *ServerInterfaceWrapper) GetDataproducts(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDataproductsParams

	// ------------- Optional query parameter "limit" -------------
	if paramValue := r.URL.Query().Get("limit"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter limit: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------
	if paramValue := r.URL.Query().Get("offset"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter offset: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDataproducts(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// CreateDataproduct operation middleware
func (siw *ServerInterfaceWrapper) CreateDataproduct(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDataproduct(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// DeleteDataproduct operation middleware
func (siw *ServerInterfaceWrapper) DeleteDataproduct(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDataproduct(w, r, id)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetDataproduct operation middleware
func (siw *ServerInterfaceWrapper) GetDataproduct(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDataproduct(w, r, id)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UpdateDataproduct operation middleware
func (siw *ServerInterfaceWrapper) UpdateDataproduct(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateDataproduct(w, r, id)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// CreateDataset operation middleware
func (siw *ServerInterfaceWrapper) CreateDataset(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDataset(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// DeleteDataset operation middleware
func (siw *ServerInterfaceWrapper) DeleteDataset(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDataset(w, r, id)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetDataset operation middleware
func (siw *ServerInterfaceWrapper) GetDataset(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDataset(w, r, id)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// UpdateDataset operation middleware
func (siw *ServerInterfaceWrapper) UpdateDataset(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateDataset(w, r, id)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Search operation middleware
func (siw *ServerInterfaceWrapper) Search(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchParams

	// ------------- Optional query parameter "q" -------------
	if paramValue := r.URL.Query().Get("q"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter q: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------
	if paramValue := r.URL.Query().Get("limit"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter limit: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------
	if paramValue := r.URL.Query().Get("offset"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		http.Error(w, fmt.Sprintf("Invalid format for parameter offset: %s", err), http.StatusBadRequest)
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Search(w, r, params)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetUserInfo operation middleware
func (siw *ServerInterfaceWrapper) GetUserInfo(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{""})

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserInfo(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL     string
	BaseRouter  chi.Router
	Middlewares []MiddlewareFunc
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dataproducts", wrapper.GetDataproducts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dataproducts", wrapper.CreateDataproduct)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/dataproducts/{id}", wrapper.DeleteDataproduct)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dataproducts/{id}", wrapper.GetDataproduct)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/dataproducts/{id}", wrapper.UpdateDataproduct)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/datasets", wrapper.CreateDataset)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/datasets/{id}", wrapper.DeleteDataset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/datasets/{id}", wrapper.GetDataset)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/datasets/{id}", wrapper.UpdateDataset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/search", wrapper.Search)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/userinfo", wrapper.GetUserInfo)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RY32/bNhD+VwRuj5rtdhtQ6C2dhyLY0GBL+xQExUU624wlUiFP8YzA//vAH7Isi5bs",
	"LnW9N1k83o/v7vtM6oWlsiilQEGaJS9MpwsswD6+5/O/KlRr81wqWaIijnYlAwKNZB5pXSJLmCbFxZxt",
	"YmP5iCl94VlwmeAhx8DKJmYKnyquMGPJ3a6XeBuu3n0f17vlg7EyfqdAUCqZVSl1800VAqFNaCZVAcQS",
	"4xR/Il4gi7tZ+oh2Mycs7MOPCmcsYT+MG8TGHq7x1G24rYoC1NoW6nyCUmB/Z6hTxUviUgSBOYDXEtcr",
	"qbJ2Jl1U94LloOlLITM+46eULaDAoH+5EqiGMLixRraRpQy60Xk1H+697blNxe+o48fbRu5XuNOxQ8Ph",
	"57U9GA98/lSPeF9pWyr42fCTdmjIv7LXB+EvOd95/yBljiB6cTM7OqnGTb09KNUz3AHr1Kzdi6N488mY",
	"9tVjffUk/cnHQlEVZm+g0Caxj7jqlYuh9n0dJy+DXB5PFzMEqAfnkujyH3nhS+6QwXGklxI3dWvaOBBC",
	"Ee45QrEEglzOUQw3w/oJxb1FUOnib9RVTr8LCrER/0lRlfQq+nIMU3dTcnSNWaXy4SKNkQ8RtzhdVzAE",
	"wD63m+PATkvrX5AuYY5B2n/WqK7FTAawLIDnJ0KGUJwkAOGhdJFrd10kDK8xrRSn9a1phD/PSLnkeFXR",
	"wmYgWOJf1eAm7HFFzT88ySUaXpjR8AAQJ3MOYx+vplcsZs+otKUfezOaWFEqUUDJWcJ+Hk1Gbw1dgBY2",
	"+ngHdvti7rSiRWP2J9cUQZ5HLWvrWIGxuc5Ywj4gTdvrJSgokFBpltz54hxBt7XlvOCmOjeaLvQMqpxY",
	"8ubXbdFcEM6NZm7isBs5m7kxCviZBNzcmw7qUgrtuvB2MnHNEITCIgBlmfPUVjd+1E7NGudHHyTrke7O",
	"0L5Ysps/3NtS6kAPfrPHpQgigauoTZZ2G5zhtGVhphU1vZfZ+qQy+6rb++fdbBwtWqC+ebVoe6HiIDpZ",
	"pKs0Ra1nVZ6vW4yzA7jLtbv7zb0xaDFg/MKzjcM+R8JuF6b2fQS9HXBG7Q7sUWHPa2MaXU+NtJq3hqTN",
	"hFu1bVSHVIW7076v290B/+VQNVlkJ28Iq7hPG3bxiFacFtH2EN8vExcBzQVxvwpA/LnMYHDonNEFIPt9",
	"lGZyLqVxOB/JmVpf6u8PR0q7+ys7JOtu9RsCbQKcQc59mFeWcgP1aTIeQruRcLc6yCSN/z/p/oB0EACv",
	"0pdQ/eQcU3e8AIfQasT3OwF2fi04S1dOFltt75oHLzLuKhpxEfm7UruNbpmd43zQ/SpwxCnBp6/sLj+v",
	"w1esJ9Y3PvFl3ctMEyuNqr7bBts4R4qMUWStAtK1/TzwDcd2G+OQmgzOq7VQz3Xv7BcYtiAqdTIe5zKF",
	"fCE1Je8m7yZjc383ILeNBGQwyvB5ZBBUYiTgeSRkn3HA8H7zbwAAAP//MOUwNDkaAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

