-- +goose Up

ALTER TABLE datasource_bigquery
ADD COLUMN last_modified TIMESTAMPTZ NOT NULL DEFAULT '2001-01-01 00:00:00',
ADD COLUMN created TIMESTAMPTZ NOT NULL DEFAULT '2001-01-01 00:00:00',
ADD COLUMN expires TIMESTAMPTZ,
ADD COLUMN table_type TEXT NOT NULL DEFAULT 'TABLE';

ALTER TABLE datasource_bigquery
ALTER COLUMN last_modified DROP DEFAULT,
ALTER COLUMN created DROP DEFAULT,
ALTER COLUMN table_type DROP DEFAULT
;
