name: Deploy metabase

on:
  workflow_run:
    workflows: [ "Build and Deploy Nada Backend" ]
    types:
      - completed
    branches:
      - '*'
    paths:
      - '.metabase_version'
      - '.nais/dev/metabase/**'
      - '.nais/prod/metabase/**'
      - '.nais/vars.yaml'

permissions:
  contents: read
  id-token: write

jobs:
  deploy-dev:
    name: Deploy to NAIS dev
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
      - name: Read Metabase Version
        id: read_metabase_version
        run: echo "METABASE_VERSION=$(cat .metabase_version)" >> $GITHUB_ENV
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev/metabase/gcp.yaml
          VAR: version=${{ env.METABASE_VERSION }}
          VARS: .nais/vars.yaml

  deploy-prod:
    name: Deploy to NAIS prod
    runs-on: ubuntu-latest
    needs: deploy-dev
    if: github.ref == 'refs/heads/main' && github.actor != 'dependabot[bot]' && github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
      - name: Read Metabase Version
        id: read_metabase_version
        run: echo "METABASE_VERSION=$(cat .metabase_version)" >> $GITHUB_ENV
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/prod/metabase/gcp.yaml
          VAR: version=${{ env.METABASE_VERSION }}
          VARS: .nais/vars.yaml
          TIMEOUT: 15m
